<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Demonstration</name>
   <tag></tag>
   <elementGuidId>04371ee4-d8ac-46cf-91a8-44ec9c1ced4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='swup']/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.mb-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5c5d9fbb-664b-48d4-8f2a-9887616beef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0</value>
      <webElementGuid>85eb7d24-51f3-4111-bdd4-5b9e1dbb3bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demonstration</value>
      <webElementGuid>b6c3859d-7802-4fe9-99a3-71c4b7c11366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swup&quot;)/div[@class=&quot;headline&quot;]/div[@class=&quot;container&quot;]/h1[@class=&quot;mb-0&quot;]</value>
      <webElementGuid>d9cc50cc-5ee3-4206-a0b9-9ec9389918b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='swup']/div/div/h1</value>
      <webElementGuid>a8b3e790-091e-4e38-898b-b4c17f50977d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>7ee23563-55fb-4c43-afc8-bc7ec6cacf29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Demonstration' or . = 'Demonstration')]</value>
      <webElementGuid>0bbf9f7d-5464-4380-8c86-9aa95216b97a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
