<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_chat-widget</name>
   <tag></tag>
   <elementGuidId>b42abb6c-d790-41ea-bbc4-91ad59fac047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='chat-widget']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chat-widget</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0e77dd75-fcc1-463d-8952-ff58314a7d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay; microphone *; camera *; display-capture *; picture-in-picture *; fullscreen *;</value>
      <webElementGuid>363f0f67-2060-41ec-8162-7987aeaf614d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://secure.livechatinc.com/customer/action/open_chat?license_id=4618001&amp;group=0&amp;embedded=1&amp;widget_version=3&amp;unique_groups=0</value>
      <webElementGuid>3e7d4991-0d9b-4a91-9304-21e25a38bd77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c55f5562-eea0-4e06-9877-1a489c089b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chat-widget</value>
      <webElementGuid>fe25fecd-b357-4862-a4b2-203c4da2654e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chat-widget</value>
      <webElementGuid>518c50b3-2c23-40f8-a5bd-a8bd1db7ca44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>LiveChat chat widget</value>
      <webElementGuid>81625c46-43bb-43f0-ba76-7f10f80cbfac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>54cbfcbe-e8cc-4490-8893-b97ba21172bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chat-widget&quot;)</value>
      <webElementGuid>e22d9a8a-5bec-4a69-93f3-d8851fa85f32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='chat-widget']</value>
      <webElementGuid>75b087e0-b33c-444c-81a1-4154e4321d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chat-widget-container']/iframe</value>
      <webElementGuid>4d11b4c6-3c2d-4761-911e-6b2960f3ac6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d1c4b376-69f3-4abf-ae05-777ad58b07b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://secure.livechatinc.com/customer/action/open_chat?license_id=4618001&amp;group=0&amp;embedded=1&amp;widget_version=3&amp;unique_groups=0' and @id = 'chat-widget' and @name = 'chat-widget' and @title = 'LiveChat chat widget']</value>
      <webElementGuid>790da979-241c-45de-bb04-10d30dd78d3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
