<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_business_name</name>
   <tag></tag>
   <elementGuidId>f12b5b57-6e8f-4910-ae5a-a2a7c08c7b9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='business_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;business_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a0f5073-4cef-4c39-94ce-5a374a823df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>business_name</value>
      <webElementGuid>b7a3d426-b102-45f9-9f9a-9c303053429f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23819738-3770-4641-96dd-7d547bba5e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>business_name form-control</value>
      <webElementGuid>46013cec-d45e-42d7-baf5-7b05dfb3f248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Business Name</value>
      <webElementGuid>19affa55-34d2-430d-84f4-bc2b6e92d6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swup&quot;)/section[@class=&quot;grey-box mt1&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-6&quot;]/div[@class=&quot;demo_form bgb br8 p3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;border rounded-4 p-4 p-md-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 form-group&quot;]/div[1]/div[@class=&quot;form&quot;]/div[@class=&quot;form-floating mb-3&quot;]/input[@class=&quot;business_name form-control&quot;]</value>
      <webElementGuid>75ee468d-bb4d-49d9-a1db-b4fb4dde3cc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='business_name']</value>
      <webElementGuid>d43dd163-4300-4593-bd26-1a880354bf34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='swup']/section/div/div/div/div/div/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>ddbc7089-ceec-4c26-a9ac-425fa326d01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e82f6a02-7c4f-4413-9840-16c873608034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'business_name' and @type = 'text' and @placeholder = 'Business Name']</value>
      <webElementGuid>aff3e3d5-5ccf-4686-bdf2-d46d9ee0b1ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
